services:
  - type: web
    name: n8n-server
    env: docker
    plan: standard # Recommended for n8n performance
    healthCheckPath: /healthz
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 10
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
      - key: GENERIC_TIMEZONE
        value: Europe/Istanbul
      - key: WEBHOOK_URL
        sync: false
        placeholder: "https://your-n8n-app-name.onrender.com/"
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false
        placeholder: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
        placeholder: "password"
